spring:
  rabbitmq:
  host: localhost
  port: 5672
  username: "guest"
  password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

  endpoint:
    health:
      probes:
        enabled: true

    shutdown:
      enabled: true

  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true

endpoints:
  shutdown:
    enable: true

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://localhost:8070/eureka/

server:
   port: 8095

info:
  app:
    name: gatewayserver
    description: Safe Ride Microservices Gateway Server
    version: "0.0.1"